//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spare_parts
    {
        public int Spare_parts_ID { get; set; }
        public string Name_of_the_spare_part { get; set; }
        public decimal Price_of_spare_parts { get; set; }
    }
}
