//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Pas
    {
        public int Id_Admin { get; set; }
        public string Password_Admin { get; set; }
        public string Login_Admin { get; set; }
    }
}
