//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id_Client { get; set; }
        public string Name { get; set; }
        public int Phone_Number { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
    }
}
