//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Device_ID { get; set; }
        public int Client_Id { get; set; }
        public string Device_Type { get; set; }
        public string Device_Model { get; set; }
        public string Problem { get; set; }
    
        public virtual User User { get; set; }
    }
}
