//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int Device_ID { get; set; }
        public string Model { get; set; }
        public string Model_Type { get; set; }
        public string Device_Type { get; set; }
        public int User_ID { get; set; }
        public string BreakdownReason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
