//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spare
    {
        public int ID_Spare_Part { get; set; }
        public string Name_of_the_spare_part { get; set; }
        public string Price { get; set; }
    }
}
