//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorbachev_KURS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_user { get; set; }
        public string pass { get; set; }
        public string login { get; set; }
        public int ID_Role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Device Device { get; set; }
        public virtual Client Client { get; set; }
    }
}
